import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"

const dirname = path.dirname(fileURLToPath(import.meta.url))
const rootDir = path.resolve(dirname, "..")
const localesDir = path.join(rootDir, "locales")
const outputFilePath = path.join(rootDir, "types", "l10nKeys.d.ts")

function generateTypes() {
    if (!fs.existsSync(localesDir)) {
        console.error(`Locales directory not found at ${localesDir}`)
        process.exit(1)
    }

    // Find the first .po file in the directory
    const poFiles = fs
        .readdirSync(localesDir)
        .filter((file) => file.endsWith(".po"))
        .sort()

    if (poFiles.length === 0) {
        console.error("No .po files found in the locales directory")
        process.exit(1)
    }

    const poFilePath = path.join(localesDir, poFiles[0])
    console.log(`Generating types from: ${poFiles[0]}`)

    const content = fs.readFileSync(poFilePath, "utf-8")
    const msgidRegex = /^msgid\s+"(.*)"/gm

    const keys = []
    for (const match of Array.from(content.matchAll(msgidRegex))) {
        const key = match[1]
        if (key && key.startsWith("l10n.")) {
            keys.push(key)
        }
    }

    const uniqueKeys = Array.from(new Set(keys)).sort()

    let typeContent = "// This file is auto-generated by scripts/generateL10nTypes.ts. Do not edit manually!\n\n"
    if (uniqueKeys.length === 0) {
        typeContent += "export type L10nKey = never"
    } else if (uniqueKeys.length === 1) {
        typeContent += `export type L10nKey = "${uniqueKeys[0]}"`
    } else {
        typeContent += "export type L10nKey ="
        for (const key of uniqueKeys) {
            typeContent += `\n    | "${key}"`
        }
    }

    typeContent += "\n"

    if (!fs.existsSync(path.dirname(outputFilePath))) {
        fs.mkdirSync(path.dirname(outputFilePath), { recursive: true })
    }

    fs.writeFileSync(outputFilePath, typeContent)
    console.log(`Successfully generated ${uniqueKeys.length} keys in ${outputFilePath}`)
}

generateTypes()
