name: Auto Check Demo

on:
    push:
        branches: ["main"]

jobs:
    verify:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            
            - name: Install Node
              uses: actions/setup-node@v6
              with:
                  node-version-file: ./apps/web_client/package.json
                  cache: yarn
                  cache-dependency-path: ./apps/web_client/yarn.lock
            
            - name: Install Dependencies
              working-directory: ./apps/web_client/
              run: yarn install --frozen-lockfile
            
            - name: Run Build
              working-directory: ./apps/web_client/
              run: yarn build
